version: '3.8'

services:
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY}/suna-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./backend/.env:/app/.env:ro
    environment:
      - ENV_MODE=local

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY}/suna-frontend:latest
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/.env.local:/app/.env.local:ro
    environment:
      - NODE_ENV=development
    depends_on:
      - backend