name: cambridge_ai_tutor
description: Cambridge AI Tutor mobile application for primary school children
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Navigation
  go_router: ^12.1.3
  
  # Local Storage & Offline
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # HTTP & API
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # UI Components
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  
  # Audio & Speech
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  audioplayers: ^5.2.1
  
  # Camera & Image Processing
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  image: ^4.1.3
  google_mlkit_text_recognition: ^0.10.0
  
  # Connectivity
  connectivity_plus: ^5.0.2
  
  # Permissions
  permission_handler: ^11.0.1
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # Utilities
  uuid: ^4.1.0
  intl: ^0.18.1
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4
  
  # Testing
  bloc_test: ^9.1.5
  mocktail: ^1.0.1

flutter:
  uses-material-design: true